name: V Mobile Build project 
on: 
 workflow_dispatch: {}
jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS
        unityVersion:
          - 2020.2.2f1
        projectName: 
          - "Lila's Tale and the Hidden Forest"
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: false
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          androidAppBundle: true
          androidKeystoreName: user.keystore
          #TODO: Setup da keystore_base64
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }} 
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: ${{ matrix.unityVersion }}
          buildName: ${{ matrix.projectName }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.projectName}}
          path: build
