name: Generate Mobile Build

on: 
 workflow_dispatch: {}
 push:
   branches:
   - build-mobile
 #schedule: 
  #- cron: '0 3 * * 1,3'
  
jobs:
  build:
    name: Build ${{matrix.projectName}} for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
         # - Android
          - iOS
        unityVersion:
          - 2020.2.2f1
        projectName: 
          - "Lila's Tale and the Hidden Forest"
    steps:
    
      #Checkout
      - uses: actions/checkout@v2
        with:
          lfs: false
          
      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-
          
      # Build
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: ${{ matrix.unityVersion }}
          buildName: ${{ matrix.projectName }}
          #androidAppBundle: true
          #androidKeystoreName: user.keystore
          #TODO: Setup da keystore_base64
          #androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }} 
          #androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          #androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          #androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
          
      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.projectName}}
          path: build
