name: Win VM Build project
on:
  workflow_dispatch: {}
jobs:
  buildForWindows:
    name: Build ${{matrix.projectName}} for ${{ matrix.targetPlatform }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
        unityVersion:
          - 2020.3.26f1
        projectName: 
          - "Lila's Tale and the Hidden Forest" #Nome do projeto
        projectPath:
          - RootTest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: false
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          #customImage: 'unityci/editor:ubuntu-2020.3.26f1-windows-mono-1.0.1'  
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: ${{ matrix.unityVersion }}
          buildName: ${{ matrix.projectName }}
          customParameters: -CompressWithLz4HC
          #allowDirtyBuild: true
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.projectName}}
          path: build
